### ISSUE TITLE
Stylling panel error

### ISSUE THREAD

**Issue by bellanz80** [geoign/TopoUSM-QGIS#4]
Hi! Congratulations for your work, it's great!
I'm trying to do tests and understand the complement well, because I study MDT in archeology. But I have an error: after generating the layers in the panel TopoUSM, and go to the panel Stylling, a python error occurs.
Copy the error generated by QGIS 3.2.1
Thank you so much!
Luca

2018-08-02T11: 34: 06 WARNING Traceback (most recent call last):
              File "C: / Users / UV / AppData / Roaming / QGIS / QGIS3 \ profiles \ luca / python / plugins \ TopoUSM-QGIS-master \ topousm2.py", line 234, in tabChanged
              if i == 1: self.doTableRefresh ()
              File "C: / Users / UV / AppData / Roaming / QGIS / QGIS3 \ profiles \ luca / python / plugins \ TopoUSM-QGIS-master \ topousm2.py", line 239, in doTableRefresh
              usmfiles = [usmlayer.dataProvider (). dataSourceUri () for usmlayer in self.usmlayers]
              File "C: / Users / UV / AppData / Roaming / QGIS / QGIS3 \ profiles \ luca / python / plugins \ TopoUSM-QGIS-master \ topousm2.py", line 239, in
              usmfiles = [usmlayer.dataProvider (). dataSourceUri () for usmlayer in self.usmlayers]
             RuntimeError: wrapped C / C ++ object of type QgsRasterLayer has been deleted

![error_topousm](https://user-images.githubusercontent.com/38449926/43597925-16f281c4-9649-11e8-9a81-1bebe39d9f71.PNG)

**Comment by geoign** [comment]
Hi Luca,

Thanks for reporting! 
It is great to know that people in other criteria get interested in my plugin.

I am planning to modify not to load the usm raster files immediately after the completion of the processing. It makes the workflow more straightforward and reduces the chance that the layer handling gets broken such like in your error.
The update is going to be made in the next few days. Stay tuned!

Fumi

**Comment by bellanz80** [comment]
Thank you very much Fumi!
Yesterday I tried other raster, and there was no problem. I have noticed some blocking of the plug just referring to the automatic loading of the layer, so the update will look great!
I will be very aware of your work, and I hope to learn how to use it well, it has a lot of potential, but I must understand the modifications made to the DEM, because I work with very small elements, 10-20 meters in size.
Thank you very much! :)
Luca
